import { writeFileSync } from 'node:fs';
import { initialCatalog } from '../src/lib/seed';
const data = initialCatalog(false);
const groups = [
  ['folder', data.folders],
  ['scene', data.scenes],
  ['settings', [data.settings]],
] as const;
const rows = groups.flatMap(([entity, items]) =>
  items.map(
    (item) => `('${entity}', '${item.id}', '${JSON.stringify(item).replaceAll("'", "''")}'::jsonb)`,
  ),
);
writeFileSync(
  'supabase/migrations/002_seed.sql',
  `-- Generated by scripts/generate-seed.ts. Empty production catalog; no demo estates or products.\n-- Real destination URLs must be configured in CMS. Never re-seeds over existing records.\ninsert into public.catalog_entries (entity,id,payload) values\n${rows.join(',\n')}\non conflict (entity,id) do nothing;\n`,
  'utf8',
);
